version: '3.7'
services:
  backend:
    container_name: docker_backend
    hostname: iim_backend
    build: ./backend
    ports:
      - '4001:4001'
  mysql:
    container_name: docker_mysql
    hostname: docker_mysql
    build: ./backend
    ports:
    - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
  frontend:
    container_name: docker_frontend
    hostname: docker_frontend
    build: ./frontend
    ports:
    - '4000:3000'

